version: "1"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env

  my-database: 
    image: "mysql:latest"     
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306      