version: "3.7"

services:
  blccu-ecr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLATFORM: linux/amd64
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod
  # my-database: 
  #   image: "mysql:latest"     
  #   restart: always
  #   env_file:
  #     - ./.env.prod
  #   environment:
  #     MYSQL_DATABASE: 'mydocker'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306      