version: "1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/my-app/app
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 8081      
    depends_on:
      - redis
  my-database: 
    image: "mysql:latest"    
    environment:
      DATABASE_TYPE: 'mysql'
      DATABASE_HOST: 'localhost'
      DATABASE_PORT:3306
      DATABASE_USERNAME:root
      DATABASE_PASSWORD:root
      DATABASE_DATABASE:localDB